"""
GeoRakshak — Sensor Simulator

Generates realistic NER sensor readings and publishes via MQTT.
Uses the same message format as the real ESP32 firmware, so the
backend treats simulator and real hardware identically.

Scenarios:
  NORMAL          — Typical monsoon baseline
  HEAVY_RAIN      — Intense rainfall event
  GROUND_MOVEMENT — Slope displacement detected
  CRITICAL        — All danger signals elevated
  SENSOR_FAILURE  — Intermittent/missing data

NOTE: All data generated by this simulator is SYNTHETIC.
"""
import json
import time
import random
import math
import os
from datetime import datetime

try:
    import paho.mqtt.client as mqtt
except ImportError:
    mqtt = None

try:
    import httpx
except ImportError:
    httpx = None


# ─── STATION DEFINITIONS (NER Demo Locations) ────────────────

STATIONS = [
    {"id": "GR-S001", "name": "Shillong Peak", "lat": 25.5788, "lon": 91.8933, "alt": 1965},
    {"id": "GR-S002", "name": "Sohra (Cherrapunji)", "lat": 25.2961, "lon": 91.7320, "alt": 1484},
    {"id": "GR-S003", "name": "Guwahati Hill", "lat": 26.1445, "lon": 91.7362, "alt": 55},
    {"id": "GR-S004", "name": "Aizawl Ridge", "lat": 23.7271, "lon": 92.7176, "alt": 1132},
    {"id": "GR-S005", "name": "Itanagar Slope", "lat": 27.0844, "lon": 93.6053, "alt": 320},
    {"id": "GR-S006", "name": "Kohima Highland", "lat": 25.6751, "lon": 94.1086, "alt": 1444},
    {"id": "GR-S007", "name": "Mawsynram", "lat": 25.2972, "lon": 91.5822, "alt": 1401},
    {"id": "GR-S008", "name": "Nongstoin", "lat": 25.5218, "lon": 91.2654, "alt": 1300},
]


# ─── SCENARIO GENERATORS ─────────────────────────────────────

def _normal(station: dict, t: float, intensity: float = 1.0) -> dict:
    """Typical monsoon conditions — low/moderate readings."""
    return {
        "device_id": station["id"],
        "timestamp": datetime.utcnow().isoformat(),
        "latitude": station["lat"],
        "longitude": station["lon"],
        "rainfall_mm": random.uniform(0.5, 5) * intensity,
        "rainfall_1h": random.uniform(2, 12) * intensity,
        "rainfall_24h": random.uniform(8, 30) * intensity,
        "soil_moisture": random.uniform(28, 45) + 5 * math.sin(t / 10),
        "tilt_x": random.uniform(0.03, 0.15),
        "tilt_y": random.uniform(0.02, 0.12),
        "temperature": random.uniform(18, 26),
        "humidity": random.uniform(70, 88),
        "battery": max(70, station.get("battery", 90) - random.uniform(0, 0.3)),
        "signal_strength": random.randint(-80, -50),
    }


def _heavy_rain(station: dict, t: float, intensity: float = 1.0) -> dict:
    """Intense rainfall — soil moisture rises, slight tilt increase."""
    return {
        "device_id": station["id"],
        "timestamp": datetime.utcnow().isoformat(),
        "latitude": station["lat"],
        "longitude": station["lon"],
        "rainfall_mm": random.uniform(8, 25) * intensity,
        "rainfall_1h": random.uniform(30, 65) * intensity,
        "rainfall_24h": random.uniform(80, 160) * intensity,
        "soil_moisture": min(95, random.uniform(65, 85) * intensity),
        "tilt_x": random.uniform(0.2, 0.8),
        "tilt_y": random.uniform(0.1, 0.5),
        "temperature": random.uniform(16, 22),
        "humidity": random.uniform(90, 99),
        "battery": max(60, station.get("battery", 85) - random.uniform(0, 0.5)),
        "signal_strength": random.randint(-90, -60),
    }


def _ground_movement(station: dict, t: float, intensity: float = 1.0) -> dict:
    """Slope displacement — elevated tilt, high moisture."""
    return {
        "device_id": station["id"],
        "timestamp": datetime.utcnow().isoformat(),
        "latitude": station["lat"],
        "longitude": station["lon"],
        "rainfall_mm": random.uniform(5, 15) * intensity,
        "rainfall_1h": random.uniform(15, 40) * intensity,
        "rainfall_24h": random.uniform(60, 120) * intensity,
        "soil_moisture": min(95, random.uniform(72, 90) * intensity),
        "tilt_x": random.uniform(1.5, 3.5) * intensity,
        "tilt_y": random.uniform(1.0, 2.8) * intensity,
        "temperature": random.uniform(17, 23),
        "humidity": random.uniform(88, 98),
        "battery": max(55, station.get("battery", 80) - random.uniform(0, 0.5)),
        "signal_strength": random.randint(-85, -55),
    }


def _critical(station: dict, t: float, intensity: float = 1.0) -> dict:
    """All danger signals elevated — pre-failure conditions."""
    return {
        "device_id": station["id"],
        "timestamp": datetime.utcnow().isoformat(),
        "latitude": station["lat"],
        "longitude": station["lon"],
        "rainfall_mm": random.uniform(15, 35) * intensity,
        "rainfall_1h": random.uniform(50, 90) * intensity,
        "rainfall_24h": random.uniform(130, 220) * intensity,
        "soil_moisture": min(99, random.uniform(85, 96) * intensity),
        "tilt_x": random.uniform(3.0, 6.0) * intensity,
        "tilt_y": random.uniform(2.5, 5.0) * intensity,
        "temperature": random.uniform(15, 20),
        "humidity": random.uniform(95, 99),
        "battery": max(40, station.get("battery", 75) - random.uniform(0, 0.8)),
        "signal_strength": random.randint(-95, -70),
    }


SCENARIO_MAP = {
    "NORMAL": _normal,
    "HEAVY_RAIN": _heavy_rain,
    "GROUND_MOVEMENT": _ground_movement,
    "CRITICAL": _critical,
}


# ─── MAIN SIMULATOR ──────────────────────────────────────────

class SensorSimulator:
    """
    Publishes sensor data on MQTT topic: georakshak/sensors/{station_id}
    Optionally also POSTs to the HTTP API.
    """

    def __init__(self, mqtt_host: str = "localhost", mqtt_port: int = 1883, api_url: str = None):
        self.mqtt_host = mqtt_host
        self.mqtt_port = mqtt_port
        self.api_url = api_url
        self.client = None
        self.scenario = "NORMAL"
        self.intensity = 1.0
        self.running = False
        self.tick = 0

    def connect_mqtt(self):
        if mqtt is None:
            print("[WARN] paho-mqtt not installed, MQTT disabled")
            return
        self.client = mqtt.Client(client_id="georakshak-simulator")
        try:
            self.client.connect(self.mqtt_host, self.mqtt_port)
            self.client.loop_start()
            print(f"[MQTT] Connected to {self.mqtt_host}:{self.mqtt_port}")
        except Exception as e:
            print(f"[MQTT] Connection failed: {e}")
            self.client = None

    def publish(self, station: dict, data: dict):
        topic = f"georakshak/sensors/{station['id']}"
        payload = json.dumps(data)

        # MQTT publish
        if self.client:
            self.client.publish(topic, payload)

        # HTTP fallback/parallel
        if self.api_url and httpx:
            try:
                httpx.post(f"{self.api_url}/api/sensors/readings", json=data, timeout=5)
            except Exception as e:
                print(f"[HTTP] Failed for {station['id']}: {e}")

    def set_scenario(self, scenario: str, intensity: float = 1.0):
        self.scenario = scenario
        self.intensity = intensity
        print(f"[SIM] Scenario changed to {scenario} (intensity={intensity})")

    def run(self, interval: float = 5.0, stations: list = None):
        """Run the simulator loop."""
        self.connect_mqtt()
        self.running = True
        target_stations = stations or STATIONS

        print(f"[SIM] Starting simulator | Scenario: {self.scenario} | Stations: {len(target_stations)} | Interval: {interval}s")

        try:
            while self.running:
                generator = SCENARIO_MAP.get(self.scenario, _normal)
                for station in target_stations:
                    data = generator(station, self.tick, self.intensity)
                    self.publish(station, data)
                    print(f"  [{station['id']}] rain_1h={data['rainfall_1h']:.1f}mm soil={data['soil_moisture']:.1f}% tilt={data['tilt_x']:.2f}°")
                self.tick += 1
                time.sleep(interval)
        except KeyboardInterrupt:
            print("\n[SIM] Stopped")
        finally:
            self.running = False
            if self.client:
                self.client.loop_stop()
                self.client.disconnect()


# ─── CLI ──────────────────────────────────────────────────────

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="GeoRakshak Sensor Simulator")
    parser.add_argument("--scenario", default="NORMAL", choices=list(SCENARIO_MAP.keys()))
    parser.add_argument("--intensity", type=float, default=1.0)
    parser.add_argument("--interval", type=float, default=5.0)
    parser.add_argument("--mqtt-host", default=os.environ.get("MQTT_BROKER_HOST", "localhost"))
    parser.add_argument("--mqtt-port", type=int, default=int(os.environ.get("MQTT_BROKER_PORT", "1883")))
    parser.add_argument("--api-url", default=os.environ.get("API_URL", "http://localhost:8000"))
    args = parser.parse_args()

    sim = SensorSimulator(
        mqtt_host=args.mqtt_host,
        mqtt_port=args.mqtt_port,
        api_url=args.api_url,
    )
    sim.set_scenario(args.scenario, args.intensity)
    sim.run(interval=args.interval)
